### ISSUE TITLE
don't have phpunit.xml in stubs folder, may cause problem

### ISSUE THREAD

**Issue by tradzero** [bobbybouwmann/dusk-demo#1]
i try to run `php artisan dusk`, but errors happened 
![image](https://cloud.githubusercontent.com/assets/13845447/21973220/045192ae-dbfa-11e6-9d7c-6a0460049307.png), it maybe because missing file 'phpunit.xml' in stubs folder.
errors happen in 'vendor\laravel\dusk\src\Console\DuskCommand.php' line 127

**Comment by bobbybouwmann** [comment]
I can't replicate this error... If the `phpunit.xml` file is missing in the stubs folder we should create a PR on the `dusk` repository.

**Comment by JayBizzle** [comment]
I already submitted a PR to fix this which has been merged laravel/dusk#5

**Comment by bobbybouwmann** [comment]
@JayBizzle Great! Thanks for the PR
